#!/usr/bin/env python3
"""
Expanded Story Library for KDP Publishing Machine
Add these to publishing_machine.py STORY_LIBRARY
"""

ADDITIONAL_STORIES_EN = {
    "luna_moon": {
        "title": "Luna and the Moon",
        "subtitle": "A Bedtime Story",
        "series": "Nighttime Tales",
        "book_number": 1,
        "age": "3-6",
        "palette": "bedtime",
        "description": "A little owl learns about the magic of the night sky and finds peace in bedtime.",
        "keywords": ["owl", "moon", "bedtime", "night", "stars", "sleep"],
        "new_words": ["glow", "gentle", "silver", "whisper", "peaceful", "dream"],
        "chapters": [
            {"type": "copyright"},
            {"type": "dedication", "text": "For sleepy little ones everywhere"},
            {"type": "title_page"},
            {"type": "illustration", "desc": "luna_on_branch"},
            {"type": "text", "content": "Luna was a little owl who lived in a tall oak tree. She had soft, gray feathers and big, golden eyes."},
            {"type": "text", "content": "Every night, when the sun went to sleep, Luna would wake up and look at the sky."},
            {"type": "illustration", "desc": "moon_rising"},
            {"type": "text", "content": "Up in the sky, Luna saw the big, round moon. It had a soft, silvery glow that lit up the night."},
            {"type": "vocab", "word": "glow", "definition": "To shine with a soft, warm light", "example": "The fireflies made a gentle glow in the garden."},
            {"type": "vocab", "word": "silver", "definition": "A shiny gray-white color, like the moon", "example": "Grandma's hair turned silver over the years."},
            {"type": "text", "content": "Hello, Moon! Luna would call out in her gentle voice."},
            {"type": "vocab", "word": "gentle", "definition": "Soft and kind, not rough or loud", "example": "The gentle breeze felt nice on a hot day."},
            {"type": "illustration", "desc": "owl_whispering"},
            {"type": "text", "content": "The wind would whisper through the leaves, making a soft shhh sound."},
            {"type": "vocab", "word": "whisper", "definition": "To speak very softly and quietly", "example": "The librarian asked us to whisper in the library."},
            {"type": "text", "content": "Luna felt so peaceful watching the moon rise high in the dark sky."},
            {"type": "vocab", "word": "peaceful", "definition": "Calm, quiet, and happy", "example": "The lake was peaceful in the early morning."},
            {"type": "illustration", "desc": "starry_sky"},
            {"type": "text", "content": "The stars twinkled all around like tiny night lights, keeping watch over the world."},
            {"type": "text", "content": "Luna tucked her wings close and closed her big golden eyes."},
            {"type": "text", "content": "She dreamed of flying over silver clouds with her friend the moon."},
            {"type": "vocab", "word": "dream", "definition": "Pictures and stories in your mind while you sleep", "example": "I had a dream about flying last night."},
            {"type": "illustration", "desc": "luna_sleeping"},
            {"type": "text", "content": "Goodnight, Luna. Goodnight, Moon. Goodnight, stars. Sleep tight."},
            {"type": "text", "content": "The End."},
            {"type": "back_matter"},
        ]
    },
    "benny_bear": {
        "title": "Benny Bear's First Honey",
        "subtitle": "A Story About Trying New Things",
        "series": "Forest Friends",
        "book_number": 1,
        "age": "4-7",
        "palette": "warm",
        "description": "A curious little bear learns that trying new things can lead to sweet rewards.",
        "keywords": ["bear", "honey", "forest", "trying", "courage", "sweet"],
        "new_words": ["curious", "wobble", "sticky", "delicious", "proud", "adventure"],
        "chapters": [
            {"type": "copyright"},
            {"type": "dedication", "text": "For every child brave enough to try"},
            {"type": "title_page"},
            {"type": "illustration", "desc": "benny_in_cave"},
            {"type": "text", "content": "Benny was a small brown bear who lived in a cozy cave with his mama."},
            {"type": "text", "content": "Benny was very curious about everything. He always wanted to know what was over the next hill."},
            {"type": "vocab", "word": "curious", "definition": "Wanting to learn and know about things", "example": "The curious cat explored every corner of the house."},
            {"type": "illustration", "desc": "honey_smell"},
            {"type": "text", "content": "One sunny morning, Benny smelled something sweet and wonderful coming from the forest."},
            {"type": "text", "content": "What is that yummy smell? Benny wondered, sniffing the air with his big bear nose."},
            {"type": "text", "content": "He followed his nose through the forest on a big adventure."},
            {"type": "vocab", "word": "adventure", "definition": "An exciting trip to explore new places", "example": "We went on an adventure to find the hidden waterfall."},
            {"type": "illustration", "desc": "honey_tree"},
            {"type": "text", "content": "Benny found a tall tree with something golden dripping down the trunk."},
            {"type": "text", "content": "He tried to climb up, but his little paws made him wobble."},
            {"type": "vocab", "word": "wobble", "definition": "To shake and move unsteadily", "example": "The jelly on my plate did a wobble."},
            {"type": "illustration", "desc": "climbing_bear"},
            {"type": "text", "content": "Benny tried again. Up, up, up he climbed, holding on tight!"},
            {"type": "text", "content": "He found a honeycomb full of golden, sticky honey."},
            {"type": "vocab", "word": "sticky", "definition": "When something clings to your fingers", "example": "The maple syrup was sticky on my pancakes."},
            {"type": "text", "content": "Benny took one tiny taste with his pink tongue. Mmmm!"},
            {"type": "vocab", "word": "delicious", "definition": "Tasting very, very good", "example": "The chocolate cake was absolutely delicious."},
            {"type": "illustration", "desc": "happy_bear"},
            {"type": "text", "content": "Benny climbed down the tree, feeling very proud of himself."},
            {"type": "vocab", "word": "proud", "definition": "Feeling happy about something you did", "example": "I felt proud when I finished the puzzle by myself."},
            {"type": "text", "content": "He couldn't wait to tell his mama bear about his adventure and share some honey."},
            {"type": "text", "content": "Sometimes the best things are worth a little wobble!"},
            {"type": "text", "content": "The End."},
            {"type": "back_matter"},
        ]
    },
    "mia_rainbow": {
        "title": "Mia Chases the Rainbow",
        "subtitle": "A Story About Colors",
        "series": "Colorful World",
        "book_number": 1,
        "age": "3-6",
        "palette": "pastel",
        "description": "A playful puppy discovers that friendship is the best treasure of all.",
        "keywords": ["rainbow", "colors", "puppy", "friendship", "chasing", "treasure"],
        "new_words": ["violet", "shimmer", "chase", "treasure", "magical", "discover"],
        "chapters": [
            {"type": "copyright"},
            {"type": "dedication", "text": "For colorful dreamers"},
            {"type": "title_page"},
            {"type": "illustration", "desc": "mia_playing"},
            {"type": "text", "content": "Mia was a happy puppy with soft golden fur and a tail that never stopped wagging."},
            {"type": "text", "content": "She loved rainy days most of all because of what came after."},
            {"type": "illustration", "desc": "rainbow_sky"},
            {"type": "text", "content": "After the rain, Mia saw something amazing in the sky."},
            {"type": "text", "content": "It was a rainbow with colors so bright they seemed to shimmer."},
            {"type": "vocab", "word": "shimmer", "definition": "To shine with a soft, glittering light", "example": "The water made a shimmer in the sunlight."},
            {"type": "text", "content": "Mia wanted to see where the rainbow ended. She ran and ran, trying to chase the colorful arc."},
            {"type": "vocab", "word": "chase", "definition": "To run after something you want to catch", "example": "The dog loves to chase squirrels in the park."},
            {"type": "illustration", "desc": "running_puppy"},
            {"type": "text", "content": "The rainbow had red, orange, yellow, green, blue, and violet."},
            {"type": "vocab", "word": "violet", "definition": "A pretty purple color", "example": "The violet flowers smelled so sweet."},
            {"type": "text", "content": "Mia ran through meadows and over little hills. She wanted to find the treasure at the rainbow's end."},
            {"type": "vocab", "word": "treasure", "definition": "Something special and valuable", "example": "Grandma's ring is a family treasure."},
            {"type": "illustration", "desc": "friend_waiting"},
            {"type": "text", "content": "But then Mia discovered something even better than gold."},
            {"type": "vocab", "word": "discover", "definition": "To find something for the first time", "example": "We discovered a secret path in the woods."},
            {"type": "text", "content": "Her friend Charlie was playing in the sunny field!"},
            {"type": "text", "content": "They played together under the magical rainbow sky."},
            {"type": "vocab", "word": "magical", "definition": "Wonderful and special, like magic", "example": "The snow made everything look magical."},
            {"type": "illustration", "desc": "friends_playing"},
            {"type": "text", "content": "Mia learned that friends are the best treasure of all."},
            {"type": "text", "content": "And rainbows are prettier when you share them with someone you love."},
            {"type": "text", "content": "The End."},
            {"type": "back_matter"},
        ]
    },
    "sammy_shell": {
        "title": "Sammy Finds His Shell",
        "subtitle": "A Story About Being Yourself",
        "series": "Ocean Friends",
        "book_number": 1,
        "age": "4-7",
        "palette": "cool",
        "description": "A small hermit crab learns that being unique is what makes you special.",
        "keywords": ["hermit crab", "shell", "ocean", "beach", "unique", "special"],
        "new_words": ["unique", "search", "ordinary", "special", "wonderful", "belong"],
        "chapters": [
            {"type": "copyright"},
            {"type": "dedication", "text": "For everyone who is perfectly themselves"},
            {"type": "title_page"},
            {"type": "illustration", "desc": "sammy_beach"},
            {"type": "text", "content": "Sammy was a small hermit crab who lived on a sandy beach near the big blue ocean."},
            {"type": "text", "content": "Sammy didn't have a shell to call his own, so he went on a search to find the perfect home."},
            {"type": "vocab", "word": "search", "definition": "To look carefully for something", "example": "We went on a search for the lost cat."},
            {"type": "illustration", "desc": "brown_shell"},
            {"type": "text", "content": "Sammy found an ordinary brown shell. It was too plain and boring."},
            {"type": "vocab", "word": "ordinary", "definition": "Normal, not special or different", "example": "It was just an ordinary Tuesday, nothing special happened."},
            {"type": "text", "content": "He found a big shell. It was too heavy to carry and made him tired."},
            {"type": "illustration", "desc": "sad_crab"},
            {"type": "text", "content": "Sammy felt sad. Would he ever find where he belonged?"},
            {"type": "vocab", "word": "belong", "definition": "To feel happy and right in a place", "example": "I feel like I belong with my best friends."},
            {"type": "text", "content": "Then Sammy saw something sparkly by the pink coral."},
            {"type": "illustration", "desc": "sparkly_shell"},
            {"type": "text", "content": "It was a small shell with swirls of blue and green, like the ocean waves."},
            {"type": "text", "content": "This shell is unique, said the wise old turtle nearby."},
            {"type": "vocab", "word": "unique", "definition": "One of a kind, like no other", "example": "My fingerprint is unique to me."},
            {"type": "text", "content": "Sammy tried it on. It fit perfectly, like it was made just for him!"},
            {"type": "text", "content": "You are special just the way you are, said the turtle with a smile."},
            {"type": "vocab", "word": "special", "definition": "Important and different in a good way", "example": "My birthday is a special day for me."},
            {"type": "illustration", "desc": "happy_sammy"},
            {"type": "text", "content": "Sammy felt wonderful in his new home."},
            {"type": "vocab", "word": "wonderful", "definition": "Very good and delightful", "example": "The party was absolutely wonderful!"},
            {"type": "text", "content": "He learned that being yourself is the very best thing to be."},
            {"type": "text", "content": "And unique is the most special thing of all."},
            {"type": "text", "content": "The End."},
            {"type": "back_matter"},
        ]
    },
}

# Spanish versions
ADDITIONAL_STORIES_ES = {
    "luna_luna": {
        "title": "Luna y la Luna",
        "subtitle": "Un Cuento para Dormir",
        "series": "Cuentos de la Noche",
        "book_number": 1,
        "age": "3-6",
        "palette": "bedtime",
        "description": "Una lechuza pequeña aprende sobre la magia del cielo nocturno y encuentra paz al dormir.",
        "keywords": ["lechuza", "luna", "dormir", "noche", "estrellas", "sueño"],
        "new_words": ["brillar", "gentil", "plateado", "susurrar", "tranquilo", "soñar"],
        "chapters": [
            {"type": "copyright"},
            {"type": "dedication", "text": "Para pequeñines soñolientos en todas partes"},
            {"type": "title_page"},
            {"type": "illustration", "desc": "luna_en_rama"},
            {"type": "text", "content": "Luna era una lechuza pequeña que vivía en un roble alto. Tenía plumas grises suaves y ojos grandes y dorados."},
            {"type": "text", "content": "Cada noche, cuando el sol se iba a dormir, Luna se despertaba y miraba al cielo."},
            {"type": "illustration", "desc": "luna_saliendo"},
            {"type": "text", "content": "Arriba en el cielo, Luna veía la luna grande y redonda. Tenía un brillo plateado suave que iluminaba la noche."},
            {"type": "vocab", "word": "brillar", "definition": "Emitir una luz suave y cálida", "example": "Las luciérnagas brillaban en el jardín."},
            {"type": "vocab", "word": "plateado", "definition": "Un color gris-blanco brillante, como la luna", "example": "El pelo de la abuela se volvió plateado con los años."},
            {"type": "text", "content": "¡Hola, Luna! Luna llamaba con su voz gentil."},
            {"type": "vocab", "word": "gentil", "definition": "Suave y amable, no áspero ni fuerte", "example": "La brisa gentil se sentía bien en un día caluroso."},
            {"type": "illustration", "desc": "lechuza_susurrando"},
            {"type": "text", "content": "El viento susurraba entre las hojas, haciendo un sonido suave de shhh."},
            {"type": "vocab", "word": "susurrar", "definition": "Hablar muy bajito y suave", "example": "La bibliotecaria nos pidió susurrar en la biblioteca."},
            {"type": "text", "content": "Luna se sentía tan tranquila mirando la luna subir alto en el cielo oscuro."},
            {"type": "vocab", "word": "tranquilo", "definition": "Calmado, quieto y feliz", "example": "El lago estaba tranquilo en la madrugada."},
            {"type": "illustration", "desc": "cielo_estrellado"},
            {"type": "text", "content": "Las estrellas centelleaban alrededor como pequeñas luces de noche, cuidando al mundo."},
            {"type": "text", "content": "Luna acurrucó sus alas y cerró sus ojos dorados."},
            {"type": "text", "content": "Soñó con volar sobre nubes plateadas con su amiga la luna."},
            {"type": "vocab", "word": "soñar", "definition": "Imágenes e historias en tu mente mientras duermes", "example": "Tuve un sueño sobre volar anoche."},
            {"type": "illustration", "desc": "luna_durmiente"},
            {"type": "text", "content": "Buenas noches, Luna. Buenas noches, Luna. Buenas noches, estrellas. Que duermas bien."},
            {"type": "text", "content": "Fin."},
            {"type": "back_matter"},
        ]
    },
}

if __name__ == "__main__":
    print("Story library expansion module")
    print(f"English stories: {len(ADDITIONAL_STORIES_EN)}")
    print(f"Spanish stories: {len(ADDITIONAL_STORIES_ES)}")
    print("\nAdd these dictionaries to publishing_machine.py STORY_LIBRARY")
